### ISSUE TITLE
Instant Apps - Emoji Compat compatibility query

### ISSUE THREAD

**Issue by preraktrivedi** [android/user-interface#82]
Hi, 

Just wanted to check if `EmojiCompat` works with Instant Apps or might have limitations due to the `FontProvider` content provider?

Intermittently, I get the following crash but after relaunch app, it is successfully loaded!

```
    EmojiCompat initialization failed
    java.lang.RuntimeException: provider not found
    at android.support.text.emoji.FontRequestEmojiCompatConfig$FontRequestMetadataLoader.retrieveFontInfo(FontRequestEmojiCompatConfig.java:229)
    at android.support.text.emoji.FontRequestEmojiCompatConfig$FontRequestMetadataLoader.createMetadata(FontRequestEmojiCompatConfig.java:290)
    at android.support.text.emoji.FontRequestEmojiCompatConfig$FontRequestMetadataLoader.access$100(FontRequestEmojiCompatConfig.java:164)
    at android.support.text.emoji.FontRequestEmojiCompatConfig$FontRequestMetadataLoader$1.run(FontRequestEmojiCompatConfig.java:218)
    at android.os.Handler.handleCallback(Handler.java:790)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:164)
    at android.os.HandlerThread.run(HandlerThread.java:65)
    Caused by: android.content.pm.PackageManager$NameNotFoundException: No package found for authority: com.google.android.gms.fonts
    at android.support.v4.provider.FontsContractCompat.getProvider(FontsContractCompat.java:735)
    at android.support.v4.provider.FontsContractCompat.fetchFonts(FontsContractCompat.java:715)
    at android.support.text.emoji.FontRequestEmojiCompatConfig$FontProviderHelper.fetchFonts(FontRequestEmojiCompatConfig.java:334)
    at android.support.text.emoji.FontRequestEmojiCompatConfig$FontRequestMetadataLoader.retrieveFontInfo(FontRequestEmojiCompatConfig.java:227)
    at android.support.text.emoji.FontRequestEmojiCompatConfig$FontRequestMetadataLoader.createMetadata(FontRequestEmojiCompatConfig.java:290) 
    at android.support.text.emoji.FontRequestEmojiCompatConfig$FontRequestMetadataLoader.access$100(FontRequestEmojiCompatConfig.java:164) 
    at android.support.text.emoji.FontRequestEmojiCompatConfig$FontRequestMetadataLoader$1.run(FontRequestEmojiCompatConfig.java:218) 
    at android.os.Handler.handleCallback(Handler.java:790) 
    at android.os.Handler.dispatchMessage(Handler.java:99) 
    at android.os.Looper.loop(Looper.java:164) 
    at android.os.HandlerThread.run(HandlerThread.java:65) 
```

**Comment by alexgomes09** [comment]
I am getting it too for S5 devices.
