### ISSUE TITLE
Crash on API v21

### ISSUE THREAD

**Issue by Sese-Schneider** [android/user-interface#84]
```EmojiCompat initialization failed
java.lang.RuntimeException: fetchFonts result is not OK. (1)
at android.support.text.emoji.FontRequestEmojiCompatConfig$FontRequestMetadataLoader.createMetadata(FontRequestEmojiCompatConfig.java:307)
at android.support.text.emoji.FontRequestEmojiCompatConfig$FontRequestMetadataLoader.access$100(FontRequestEmojiCompatConfig.java:164)
at android.support.text.emoji.FontRequestEmojiCompatConfig$FontRequestMetadataLoader$1.run(FontRequestEmojiCompatConfig.java:218)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:135)
at android.os.HandlerThread.run(HandlerThread.java:61)
```

Crashed on emulator.

**Comment by Sese-Schneider** [comment]
Closing this issue as it's stale for too long and probably isn't relevant anymore.
